//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public System.Guid IdAnswer { get; set; }
        public Nullable<System.Guid> IdAnsPaper { get; set; }
        public Nullable<System.Guid> IdChoices { get; set; }
        public Nullable<System.Guid> IdQuestion { get; set; }
    
        public virtual AnswerPaper AnswerPaper { get; set; }
        public virtual Choice Choice { get; set; }
        public virtual Question Question { get; set; }
    }
}
