//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.Choices = new HashSet<Choice>();
        }
    
        public System.Guid IdQuestion { get; set; }
        public Nullable<System.Guid> IdQuestionGroup { get; set; }
        public Nullable<int> NumericalOrder { get; set; }
        public Nullable<System.Guid> IdSurvey { get; set; }
        public Nullable<System.Guid> IdQuesType { get; set; }
        public string Content { get; set; }
        public string Images { get; set; }
        public Nullable<bool> IsRequired { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> LastEditedAt { get; set; }
        public string LastEditedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Choice> Choices { get; set; }
        public virtual QuestionGroup QuestionGroup { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual SurveyInfo SurveyInfo { get; set; }
    }
}
